# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://blog.staymanhou.com
title: Stayman's Blog
subtitle: 'A blog belongs to a system admin & hacker.'
author: Stayman Hou 侯越辰
simple_search: https://www.google.com/search
description: "This is Stayman's blog. Stayman is a Christian. He has some experience over system administration. Have some hacking skills. This blog covers the following topics: IT, server, Linux, dev, personal life, and Christianity. You could find helpful thing here, either technique-related or life-related. 侯越辰的博客。基督徒，系统维护，hacking。包括一下的话题：信息技术，服务器，Linux，开发，个人生活，基督教。希望你可以在这里得到技术和人生上的帮助。"

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email:

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
permalink: /blog/:year/:month/:day/:title/
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: blog/categories
markdown: rdiscount
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart
highlighter: pygments # default python pygments have been replaced by pygments.rb

paginate: 10          # Posts per page on the blog index
paginate_path: "posts/:num"  # Directory base for pagination URLs eg. /posts/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
excerpt_separator: "<!--more-->"

titlecase: true       # Converts page and post titles to titlecase

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
default_asides: [asides/recent_posts.html, custom/asides/category_cloud.html, custom/asides/short_ads.html, asides/googleplus.html, asides/github.html, custom/asides/long_ads.html] #, asides/delicious.html, asides/pinboard.html, custom/asides/category_list.html

# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
# blog_index_asides:
# post_asides:
# page_asides:

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user: StaymanHou
github_repo_count: 10
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user:
twitter_tweet_button: true

# Google +1
google_plus_one: false
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user: 111718847796837023988
googleplus_hidden: false

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name: staymansblog
disqus_show_comment_count: false

# Google Analytics
google_analytics_tracking_id: UA-53641328-1

# Facebook Like
facebook_like: false

# New Relic Browser
new_relic_license_key: 0c8384869e
new_relic_application_id: 4027352